Dev soil
walkeranthonyp/MAAT pull request #40
Opened 2022-02-16 16:52 UTC by mattecraig

I have added several models to soil_decomp, and I don't think we've merged in progress on the steady state solver yet (on dev_soil). Could alternatively merge into dev_soil_steadystate (which is not as far behind).

2022-02-17 00:03 UTC, walkeranthonyp requested changes
Awesome to see all this progress Matt. And thanks for moving this forward quickly.

A number of specific comments and requests for edits in response to this PR. Mostly housekeeping type of stuff and hopefully won't take you long. 

Please take a moment to check your codes are running once you've made the changes and then resubmit the PR into the steadystate branch.

2022-02-17 00:03 UTC, walkeranthonyp commented on run_scripts/create_default_XMLs.R
> +setwd('~/Documents/MAAT/src/functions/')
Not understanding this change. Please set this back to the original or let me know what's the problem here. 

Generally when making specific local edits like this it might be a good idea to add them to a separate branch that only records these specific local changes, and use the main feature branch for code updates that want to go into the general repo. Does that make sense? It means switching between two branches but will help keep things clean and isolate changes like this that will break others' us e of the code.

2022-02-17 00:03 UTC, walkeranthonyp commented on run_scripts/create_new_model_object
> +#!/bin/bash
Not understanding this either - is this a new file that's copy of `create_new_model_object.bs` without the file extension?

2022-02-17 00:03 UTC, walkeranthonyp commented on run_scripts/create_new_model_object_bugfix.bs.txt
> +#!/bin/bash
As above - I guess you're making some bug fixing edits.

If the fix is obvious you can just do that in the original file, no need to create a new one. 

Alternatively I'm happy to handle these problems with general MAAT code so you can focus on the soil model dev.

2022-02-17 00:03 UTC, walkeranthonyp commented on run_scripts/create_new_model_object_bugfix.bs4.txt
> +#!/bin/bash
As above. Also noting that if you want to make these new file test changes and you want to commit them please add to the local specific branch I mentioned above.

2022-02-17 00:03 UTC, walkeranthonyp commented on src/system_models/soil_decomp/mimic_xmls/out_mend2013.xml
> +<default>
This is awesome Matt. When looking for the mimic xmls maat expects the model object name as a prefix. Can you rename these using that naming convention i.e. replace `out` in your xml filename with `soil_decomp`. Can you do this for all mimic xmls.

2022-02-17 00:03 UTC, walkeranthonyp commented on src/system_models/soil_decomp/soil_decomp_SoilR_functions.R
>  # - this is where inputs would be divided among pools
Sorry to be a pest but I'd like to keep all the core SoilR functions in their own file. Could you create a new file for all these model specific solver functions etc. You can call it `soil_decomp_solver_functions.R` and remember to add the line `source(soil_decomp_solver_functions.R)` to the object script.

2022-02-17 00:03 UTC, walkeranthonyp commented on src/wrapper_functions.R
> +  print(.$model$fnames)
Please comment this out for now.

2022-02-17 17:56 UTC, mattecraig commented on run_scripts/create_default_XMLs.R
> +setwd('~/Documents/MAAT/src/functions/')
Oh, whoops, sorry that snuck in there. The problem was `Error in setwd("../src/functions/") : cannot change working directory` when running `Rscript ./run_scripts/create_default_XMLs.R "mod_obj <- 'soil_decomp'"` from the MAAT directory. It seems to get hung up if I run it from within the run_scripts directory. Can we change to `setwd('./src/functions/')` or should I be running the script differently?

2022-02-17 18:06 UTC, mattecraig commented on run_scripts/create_new_model_object
> +#!/bin/bash
Yep, that seems to be right. To be honest, I'm not understanding it either. Probably something I did way back when I started (i.e. when I had even less of a clue than I do now :) ). Deleting.

2022-02-17 18:06 UTC, mattecraig commented on run_scripts/create_new_model_object_bugfix.bs.txt
> +#!/bin/bash
Same as above.

2022-02-17 18:06 UTC, mattecraig commented on run_scripts/create_new_model_object_bugfix.bs4.txt
> +#!/bin/bash
Same as above.

2022-02-17 18:10 UTC, mattecraig commented on src/system_models/soil_decomp/mimic_xmls/out_mend2013.xml
> +<default>
Just to confirm, like this? `soil_decomp_mend2013.xml`

2022-02-17 18:12 UTC, mattecraig commented on src/wrapper_functions.R
> +  print(.$model$fnames)
will do.

2022-02-17 22:07 UTC, mattecraig commented on src/system_models/soil_decomp/soil_decomp_SoilR_functions.R
>  # - this is where inputs would be divided among pools
Done. And checked that everything still runs.

2022-02-17 22:55 UTC, walkeranthonyp commented on run_scripts/create_default_XMLs.R
> +setwd('~/Documents/MAAT/src/functions/')
Huh, interesting. I think these R scripts are supposed to be run from within the `run_scripts` directory. I guess that's inconsistent with the `setup_MAAT_project` script. How was it getting hung up?

2022-02-17 22:55 UTC, walkeranthonyp commented on src/system_models/soil_decomp/mimic_xmls/out_mend2013.xml
> +<default>
Perfect!

2022-02-18 15:58 UTC, mattecraig commented on run_scripts/create_default_XMLs.R
> +setwd('~/Documents/MAAT/src/functions/')
According to the readme in the `system_models` directory, it's all supposed to be run from the "highest level maat source code directory". I didn't look in to why it was getting hung up. Didn't throw an error after a minute or so (should run really quick), so I aborted. Can look into it more if we want to run these from the `run_scripts` directory.

2022-02-22 20:11 UTC, walkeranthonyp commented on run_scripts/create_default_XMLs.R
> +setwd('~/Documents/MAAT/src/functions/')
Hmm, I'm not sure where you're reading that on the main dir README, though I only skimmed it. From memory I always run these from within the run_scripts directory. Please keep as the original `..` for now and if there's a problem let me know what that is and I'll try to fix it.

Also can you edit the pull request to merge into `dev_soil_steadystate`

2022-02-23 18:47 UTC, walkeranthonyp approved these changes

2022-02-23 18:47 UTC, merged